version: '3.7'

services:
  ceryx:
    image: sourcelair/ceryx:latest
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
      - ${CERYX_EXTERNAL_SSL_PORT:-443}:443
    depends_on:
      - redis
    environment:
      CERYX_DISABLE_LETS_ENCRYPT: ${CERYX_DISABLE_LETS_ENCRYPT:-false}
      CERYX_SSL_DEFAULT_CERTIFICATE: ${CERYX_SSL_DEFAULT_CERTIFICATE:-/etc/ceryx/ssl/default.crt}
      CERYX_SSL_DEFAULT_KEY: ${CERYX_SSL_DEFAULT_KEY:-/etc/ceryx/ssl/default.key}
      CERYX_DOCKERIZE_EXTRA_ARGS: -no-overwrite
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      CERYX_REDIS_TIMEOUT: ${CERYX_REDIS_TIMEOUT:-100}
    command:
      - usr/local/openresty/bin/openresty
      - -g
      - daemon off;
      
  api:
    image: sourcelair/ceryx-api:latest
    depends_on:
      - redis
      - ceryx
    environment:
      CERYX_API_HOST: ${CERYX_API_HOST:-0.0.0.0}
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-localhost}
      CERYX_API_PORT: ${CERYX_API_PORT:-5555}
      CERYX_DEBUG: ${CERYX_DEBUG:-false}
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      CERYX_REDIS_TIMEOUT: ${CERYX_REDIS_TIMEOUT:-100}
      
  redis:
    image: redis:3.2.11-alpine
    volumes:
      - redis_data:/data

networks:
  default:
    attachable: true
    driver: overlay
    name: ceryx

volumes:
  redis_data:
