version: '3.7'

x-common-settings:
  &common-settings
  CERYX_DEBUG: ${CERYX_DEBUG:-true}
  CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-192.168.32.2}
  CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
  CERYX_REDIS_TIMEOUT: ${CERYX_REDIS_TIMEOUT:-100}


services:
  ceryx:
    image: sreedhar/ceryx
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
      - ${CERYX_EXTERNAL_SSL_PORT:-443}:443
    environment:
      <<: *common-settings
      CERYX_DISABLE_LETS_ENCRYPT: ${CERYX_DISABLE_LETS_ENCRYPT:-false}
      CERYX_SSL_DEFAULT_CERTIFICATE: ${CERYX_SSL_DEFAULT_CERTIFICATE:-/etc/ceryx/ssl/default.crt}
      CERYX_SSL_DEFAULT_KEY: ${CERYX_SSL_DEFAULT_KEY:-/etc/ceryx/ssl/default.key}
      CERYX_DOCKERIZE_EXTRA_ARGS: -no-overwrite
    command:
      - usr/local/openresty/bin/openresty
      - -g
      - daemon off;
      
  api:
    image: sreedhar/ceryx-api
    depends_on:
      - ceryx
    environment:
      <<: *common-settings
      CERYX_API_HOST: ${CERYX_API_HOST:-0.0.0.0}
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-localhost}
      CERYX_API_PORT: ${CERYX_API_PORT:-5555}
      
networks:
  default:
    attachable: true
    driver: overlay
    name: ceryx

