FROM ubuntu:18.04

LABEL "com.github.actions.name"="Ceryx Test"
LABEL "com.github.actions.description"="Ensure that Ceryx routes requests as expected."

LABEL "repository"="http://github.com/sourcelair/ceryx"
LABEL "maintainer"="Paris Kasidiaris <paris@sourcelair.com>"
