
FROM openresty/openresty:1.11.2.1-xenial
MAINTAINER Antonis Kalipetis <akalipetis@gmail.com>

COPY ./nginx/conf /usr/local/openresty/nginx/conf
COPY ./nginx/lualib /usr/local/openresty/nginx/lualib
COPY ./nginx/sites-enabled /usr/local/openresty/nginx/sites-enabled
