FROM openresty/openresty:1.11.2.1-alpine
MAINTAINER Antonis Kalipetis <akalipetis@gmail.com>

COPY ./nginx/conf /opt/openresty/nginx/conf
COPY ./nginx/lualib /opt/openresty/nginx/lualib
COPY ./nginx/sites-enabled /opt/openresty/nginx/sites-enabled
