#!/bin/bash
source ./env

#docker pull sreedhar/ceryx:latest

CONTAINER_NAME="ceryx-dev"

CTID=`docker ps -a | grep ${CONTAINER_NAME} | awk '{print $1}'`

echo -e "CTID = $CTID"

if [ ! -z $CTID ]; then
        docker stop ${CONTAINER_NAME}; docker rm -f ${CONTAINER_NAME}
fi

#NETWORK="docker-redis-cluster_default"
NETWORK="redis_cluster_net"

docker run -d --net ${NETWORK} --restart="unless-stopped" --name=ceryx-dev \
	-e "CERYX_DEBUG=${CERYX_DEBUG}" \
	-e "CERYX_REDIS_HOST=${CERYX_REDIS_HOST}" \
	-e "CERYX_REDIS_PORT=${CERYX_REDIS_PORT}" \
	-e "CERYX_REDIS_TIMEOUT=${CERYX_REDIS_TIMEOUT}" \
	-e "CERYX_DISABLE_LETS_ENCRYPT=${CERYX_DISABLE_LETS_ENCRYPT}" \
	-e "CERYX_SSL_DEFAULT_CERTIFICATE=${CERYX_SSL_DEFAULT_CERTIFICATE}" \
	-e "CERYX_SSL_DEFAULT_KEY=${CERYX_SSL_DEFAULT_KEY}" \
	-e "CERYX_DOCKERIZE_EXTRA_ARGS=${CERYX_DOCKERIZE_EXTRA_ARGS}" \
	-p "${CERYX_EXTERNAL_PORT}:80" \
	-p "${CERYX_EXTERNAL_SSL_PORT}:443" \
	ceryx:v1

